name: '[CRON] Validate Pool Cleaner'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'


#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  clean-validate-pool:
    name: 'Clean Validate Pool'
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a devhub

      - name: 'Delete ALL scratch orgs in Validate pool'
        run: sfp pool:delete -t validate -v devhub -a