#TODO: Slack Integration
name: '[PR] Validation'

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'



jobs:
  validate:
    name: 'Validate Changed Packages'
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a devhub


      # TODO: Implement Method to log in to SO for validation and postpone deletion until PR Close
      - name:  'Validate Source'
        run: SFDX_DISABLE_DNS_CHECK=true sfp validate -x -p validate -v devhub --loglevel debug --coveragepercent=15

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --config-file .github/config/code-analyzer.yml --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}

      - name: Check the Outputs to Determine Whether to Fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev3-violations > 0
        run: exit 1

      # TODO: Implement post-close SO deletion
      - name: 'Delete Stale Validation Org'
        if: cancelled()
        run: sf org delete scratch -p