name: '[MANUAL] PROD Release'

on:
  workflow_dispatch:
    inputs:
      pathToReleaseDef:
        description: "Path to release definition file"
        required: true

#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  PROD:
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest
    if: contains(github.ref,'refs/heads/release')
    environment:
      name: PROD

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to PROD
        run: |
          echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a prod

      # Authenticate to npm
      - uses: actions/setup-node@v4
        with:
         registry-url: 'https://npm.pkg.github.com'

      # Release to environment
      - name: 'Release to PROD'
        run: 'sfp release -u prod -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::"'
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}