name: 'PR Validation - Auto Triggered'

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'



jobs:
  validate:
    name: 'Validate Changed Packages'
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a devhub


      # TODO: Implement Method to log in to SO for validation and postpone deletion until PR Close
      - name:  'Validate Source'
        run: SFDX_DISABLE_DNS_CHECK=true sfp validate -x -p validate -v devhub --loglevel debug

# TODO: Implement Salesforce Code Analyzer
# TODO: Tailor PMD rules to the project
# TODO: Implement ESLINT for JavaScript/TypeScript files

      # TODO: Implement post-close SO deletion
      - name: 'Delete Stale Validation Org'
        if: cancelled()
        run: sf org delete scratch -p